export type DifficultyLevel = "débutant" | "intermédiaire" | "avancé";

export interface DockerCommand {
  id: string;
  command: string;
  description: string;
  example: string;
  options: string;
  notes: string;
  category: string;
  difficulty: DifficultyLevel;
  isFavorite: boolean;
}

export const defaultDockerCategories = [
  "Images",
  "Containers",
  "Run",
  "Logs & Debug",
  "Volumes",
  "Networks",
  "Docker Compose",
  "Registry",
  "Build",
  "System",
  "Avancé",
];

export const difficultyColors: Record<DifficultyLevel, { bg: string; text: string }> = {
  débutant: { bg: "bg-emerald-500/10", text: "text-emerald-400" },
  intermédiaire: { bg: "bg-amber-500/10", text: "text-amber-400" },
  avancé: { bg: "bg-rose-500/10", text: "text-rose-400" },
};

export const defaultDockerCommands: DockerCommand[] = [
  // ==================== IMAGES ====================
  {
    id: "docker-1",
    command: "docker images",
    description: "Lister toutes les images Docker locales",
    example: "docker images -a",
    options: "-a (toutes), -q (IDs seulement), --filter",
    notes: "Affiche le repository, tag, ID, date et taille",
    category: "Images",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-2",
    command: "docker pull <image>",
    description: "Télécharger une image depuis Docker Hub",
    example: "docker pull nginx:latest",
    options: "--platform (linux/amd64, linux/arm64)",
    notes: "Par défaut, télécharge depuis Docker Hub",
    category: "Images",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-3",
    command: "docker pull <image>:<tag>",
    description: "Télécharger une version spécifique d'une image",
    example: "docker pull node:18-alpine",
    options: "",
    notes: "Utiliser alpine pour des images plus légères",
    category: "Images",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-4",
    command: "docker rmi <image>",
    description: "Supprimer une image locale",
    example: "docker rmi nginx:latest",
    options: "-f (forcer)",
    notes: "Impossible si un container utilise l'image",
    category: "Images",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    id: "docker-5",
    command: "docker image prune",
    description: "Supprimer les images non utilisées (dangling)",
    example: "docker image prune -a",
    options: "-a (toutes les images non utilisées), -f (sans confirmation)",
    notes: "Libère de l'espace disque",
    category: "Images",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "docker-6",
    command: "docker tag <source> <target>",
    description: "Créer un tag pour une image",
    example: "docker tag myapp:latest myregistry/myapp:v1.0",
    options: "",
    notes: "Nécessaire avant de push vers un registry",
    category: "Images",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "docker-7",
    command: "docker history <image>",
    description: "Afficher l'historique des layers d'une image",
    example: "docker history nginx:latest",
    options: "--no-trunc (afficher complet)",
    notes: "Utile pour comprendre la composition d'une image",
    category: "Images",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  {
    id: "docker-8",
    command: "docker inspect <image>",
    description: "Afficher les détails d'une image en JSON",
    example: "docker inspect nginx:latest",
    options: "-f '{{.Config.Env}}' (format)",
    notes: "Contient toutes les métadonnées",
    category: "Images",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  {
    id: "docker-9",
    command: "docker save -o <fichier.tar> <image>",
    description: "Exporter une image vers un fichier tar",
    example: "docker save -o myapp.tar myapp:latest",
    options: "",
    notes: "Pour transférer des images sans registry",
    category: "Images",
    difficulty: "avancé",
    isFavorite: false,
  },
  {
    id: "docker-10",
    command: "docker load -i <fichier.tar>",
    description: "Importer une image depuis un fichier tar",
    example: "docker load -i myapp.tar",
    options: "",
    notes: "Restaure l'image avec ses tags",
    category: "Images",
    difficulty: "avancé",
    isFavorite: false,
  },

  // ==================== CONTAINERS ====================
  {
    id: "docker-11",
    command: "docker ps",
    description: "Lister les containers en cours d'exécution",
    example: "docker ps -a",
    options: "-a (tous), -q (IDs), --filter",
    notes: "Commande de base pour voir l'état des containers",
    category: "Containers",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-12",
    command: "docker ps -a",
    description: "Lister tous les containers (y compris arrêtés)",
    example: "docker ps -a --format 'table {{.Names}}\\t{{.Status}}'",
    options: "--format (format personnalisé)",
    notes: "Inclut les containers stoppés",
    category: "Containers",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-13",
    command: "docker start <container>",
    description: "Démarrer un container arrêté",
    example: "docker start my-nginx",
    options: "-a (attach), -i (interactive)",
    notes: "Reprend avec la config initiale",
    category: "Containers",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-14",
    command: "docker stop <container>",
    description: "Arrêter un container proprement (SIGTERM)",
    example: "docker stop my-nginx",
    options: "-t (timeout en secondes)",
    notes: "Envoie SIGTERM puis SIGKILL après timeout",
    category: "Containers",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-15",
    command: "docker restart <container>",
    description: "Redémarrer un container",
    example: "docker restart my-nginx",
    options: "-t (timeout)",
    notes: "Équivalent à stop + start",
    category: "Containers",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-16",
    command: "docker rm <container>",
    description: "Supprimer un container arrêté",
    example: "docker rm my-nginx",
    options: "-f (forcer), -v (supprimer volumes)",
    notes: "Le container doit être arrêté sauf avec -f",
    category: "Containers",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-17",
    command: "docker rm -f $(docker ps -aq)",
    description: "Supprimer tous les containers",
    example: "docker rm -f $(docker ps -aq)",
    options: "",
    notes: "ATTENTION: Supprime TOUS les containers",
    category: "Containers",
    difficulty: "avancé",
    isFavorite: true,
  },
  {
    id: "docker-18",
    command: "docker kill <container>",
    description: "Arrêter un container immédiatement (SIGKILL)",
    example: "docker kill my-nginx",
    options: "-s (signal)",
    notes: "Plus brutal que stop, pas de graceful shutdown",
    category: "Containers",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  {
    id: "docker-19",
    command: "docker rename <ancien> <nouveau>",
    description: "Renommer un container",
    example: "docker rename old-name new-name",
    options: "",
    notes: "Fonctionne même si le container tourne",
    category: "Containers",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    id: "docker-20",
    command: "docker container prune",
    description: "Supprimer tous les containers arrêtés",
    example: "docker container prune -f",
    options: "-f (sans confirmation)",
    notes: "Nettoie les containers inutilisés",
    category: "Containers",
    difficulty: "intermédiaire",
    isFavorite: true,
  },

  // ==================== RUN ====================
  {
    id: "docker-21",
    command: "docker run <image>",
    description: "Créer et démarrer un nouveau container",
    example: "docker run nginx",
    options: "Nombreuses options disponibles",
    notes: "Commande la plus utilisée de Docker",
    category: "Run",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-22",
    command: "docker run -d <image>",
    description: "Lancer un container en arrière-plan (detached)",
    example: "docker run -d nginx",
    options: "",
    notes: "Retourne l'ID du container",
    category: "Run",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-23",
    command: "docker run -it <image> <cmd>",
    description: "Lancer un container en mode interactif avec terminal",
    example: "docker run -it ubuntu bash",
    options: "-i (interactive), -t (tty/terminal)",
    notes: "Pour accéder à un shell dans le container",
    category: "Run",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-24",
    command: "docker run --name <nom> <image>",
    description: "Lancer un container avec un nom personnalisé",
    example: "docker run --name my-nginx -d nginx",
    options: "",
    notes: "Facilite la gestion et les références",
    category: "Run",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-25",
    command: "docker run -p <host>:<container> <image>",
    description: "Mapper un port du host vers le container",
    example: "docker run -p 8080:80 nginx",
    options: "-P (tous les ports exposés)",
    notes: "Format: port_host:port_container",
    category: "Run",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-26",
    command: "docker run -v <host>:<container> <image>",
    description: "Monter un volume ou répertoire",
    example: "docker run -v /data:/app/data nginx",
    options: ":ro (lecture seule)",
    notes: "Persiste les données au-delà du container",
    category: "Run",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "docker-27",
    command: "docker run -e <VAR>=<value> <image>",
    description: "Définir une variable d'environnement",
    example: "docker run -e MYSQL_ROOT_PASSWORD=secret mysql",
    options: "--env-file (fichier .env)",
    notes: "Pour configurer l'application",
    category: "Run",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "docker-28",
    command: "docker run --rm <image>",
    description: "Supprimer automatiquement le container à l'arrêt",
    example: "docker run --rm -it ubuntu bash",
    options: "",
    notes: "Idéal pour les tests et commandes ponctuelles",
    category: "Run",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "docker-29",
    command: "docker run --network <network> <image>",
    description: "Connecter le container à un réseau spécifique",
    example: "docker run --network my-network nginx",
    options: "--network=host (réseau du host)",
    notes: "Permet la communication entre containers",
    category: "Run",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "docker-30",
    command: "docker run --restart <policy> <image>",
    description: "Définir la politique de redémarrage",
    example: "docker run --restart=unless-stopped nginx",
    options: "no, on-failure, always, unless-stopped",
    notes: "Pour la haute disponibilité",
    category: "Run",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "docker-31",
    command: "docker run --memory <limit> <image>",
    description: "Limiter la mémoire du container",
    example: "docker run --memory=512m nginx",
    options: "--memory-swap (swap)",
    notes: "Évite qu'un container consomme tout",
    category: "Run",
    difficulty: "avancé",
    isFavorite: false,
  },
  {
    id: "docker-32",
    command: "docker run --cpus <limit> <image>",
    description: "Limiter l'utilisation CPU",
    example: "docker run --cpus=0.5 nginx",
    options: "--cpu-shares (priorité relative)",
    notes: "0.5 = 50% d'un CPU",
    category: "Run",
    difficulty: "avancé",
    isFavorite: false,
  },

  // ==================== LOGS & DEBUG ====================
  {
    id: "docker-33",
    command: "docker logs <container>",
    description: "Afficher les logs d'un container",
    example: "docker logs my-nginx",
    options: "-f (follow), --tail <n>, --since",
    notes: "Logs stdout et stderr",
    category: "Logs & Debug",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-34",
    command: "docker logs -f <container>",
    description: "Suivre les logs en temps réel",
    example: "docker logs -f my-nginx",
    options: "--tail 100 (dernières 100 lignes)",
    notes: "Ctrl+C pour quitter",
    category: "Logs & Debug",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-35",
    command: "docker logs --since <time> <container>",
    description: "Afficher les logs depuis un moment donné",
    example: "docker logs --since 10m my-nginx",
    options: "--until (jusqu'à)",
    notes: "Formats: 10m, 1h, 2023-01-01",
    category: "Logs & Debug",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  {
    id: "docker-36",
    command: "docker exec -it <container> <cmd>",
    description: "Exécuter une commande dans un container actif",
    example: "docker exec -it my-nginx bash",
    options: "-d (detached), -u (user)",
    notes: "Commande essentielle pour le debug",
    category: "Logs & Debug",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-37",
    command: "docker exec -it <container> sh",
    description: "Ouvrir un shell dans un container (alpine)",
    example: "docker exec -it my-app sh",
    options: "",
    notes: "Utiliser sh pour les images alpine (pas de bash)",
    category: "Logs & Debug",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-38",
    command: "docker inspect <container>",
    description: "Afficher toutes les infos d'un container",
    example: "docker inspect my-nginx",
    options: "-f '{{.NetworkSettings.IPAddress}}'",
    notes: "IP, volumes, env, network, etc.",
    category: "Logs & Debug",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "docker-39",
    command: "docker stats",
    description: "Afficher l'utilisation ressources en temps réel",
    example: "docker stats my-nginx",
    options: "--no-stream (snapshot)",
    notes: "CPU, RAM, Network, I/O",
    category: "Logs & Debug",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "docker-40",
    command: "docker top <container>",
    description: "Afficher les processus d'un container",
    example: "docker top my-nginx",
    options: "",
    notes: "Équivalent de ps dans le container",
    category: "Logs & Debug",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  {
    id: "docker-41",
    command: "docker diff <container>",
    description: "Afficher les fichiers modifiés dans un container",
    example: "docker diff my-nginx",
    options: "",
    notes: "A=ajouté, C=modifié, D=supprimé",
    category: "Logs & Debug",
    difficulty: "avancé",
    isFavorite: false,
  },
  {
    id: "docker-42",
    command: "docker cp <container>:<path> <local>",
    description: "Copier des fichiers depuis/vers un container",
    example: "docker cp my-nginx:/etc/nginx/nginx.conf ./",
    options: "",
    notes: "Fonctionne dans les deux sens",
    category: "Logs & Debug",
    difficulty: "intermédiaire",
    isFavorite: true,
  },

  // ==================== VOLUMES ====================
  {
    id: "docker-43",
    command: "docker volume ls",
    description: "Lister tous les volumes Docker",
    example: "docker volume ls",
    options: "-q (IDs), --filter",
    notes: "Volumes nommés et anonymes",
    category: "Volumes",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-44",
    command: "docker volume create <nom>",
    description: "Créer un nouveau volume nommé",
    example: "docker volume create my-data",
    options: "--driver (driver de stockage)",
    notes: "Recommandé pour la persistance",
    category: "Volumes",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-45",
    command: "docker volume inspect <volume>",
    description: "Afficher les détails d'un volume",
    example: "docker volume inspect my-data",
    options: "",
    notes: "Montre le chemin réel sur le host",
    category: "Volumes",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  {
    id: "docker-46",
    command: "docker volume rm <volume>",
    description: "Supprimer un volume",
    example: "docker volume rm my-data",
    options: "-f (forcer)",
    notes: "ATTENTION: données perdues définitivement",
    category: "Volumes",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    id: "docker-47",
    command: "docker volume prune",
    description: "Supprimer tous les volumes non utilisés",
    example: "docker volume prune -f",
    options: "-f (sans confirmation)",
    notes: "Libère de l'espace disque",
    category: "Volumes",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "docker-48",
    command: "docker run -v <volume>:<path> <image>",
    description: "Utiliser un volume nommé dans un container",
    example: "docker run -v my-data:/app/data nginx",
    options: ":ro (lecture seule)",
    notes: "Le volume est créé s'il n'existe pas",
    category: "Volumes",
    difficulty: "intermédiaire",
    isFavorite: true,
  },

  // ==================== NETWORKS ====================
  {
    id: "docker-49",
    command: "docker network ls",
    description: "Lister tous les réseaux Docker",
    example: "docker network ls",
    options: "--filter driver=bridge",
    notes: "bridge, host, none par défaut",
    category: "Networks",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-50",
    command: "docker network create <nom>",
    description: "Créer un nouveau réseau",
    example: "docker network create my-network",
    options: "--driver bridge/overlay/host",
    notes: "Permet la communication entre containers",
    category: "Networks",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "docker-51",
    command: "docker network inspect <network>",
    description: "Afficher les détails d'un réseau",
    example: "docker network inspect bridge",
    options: "",
    notes: "Liste les containers connectés",
    category: "Networks",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  {
    id: "docker-52",
    command: "docker network connect <network> <container>",
    description: "Connecter un container à un réseau",
    example: "docker network connect my-network my-nginx",
    options: "--alias (nom DNS)",
    notes: "Un container peut être sur plusieurs réseaux",
    category: "Networks",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "docker-53",
    command: "docker network disconnect <network> <container>",
    description: "Déconnecter un container d'un réseau",
    example: "docker network disconnect my-network my-nginx",
    options: "-f (forcer)",
    notes: "",
    category: "Networks",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  {
    id: "docker-54",
    command: "docker network rm <network>",
    description: "Supprimer un réseau",
    example: "docker network rm my-network",
    options: "",
    notes: "Impossible si des containers sont connectés",
    category: "Networks",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  {
    id: "docker-55",
    command: "docker network prune",
    description: "Supprimer tous les réseaux non utilisés",
    example: "docker network prune -f",
    options: "-f (sans confirmation)",
    notes: "Ne supprime pas les réseaux par défaut",
    category: "Networks",
    difficulty: "intermédiaire",
    isFavorite: false,
  },

  // ==================== DOCKER COMPOSE ====================
  {
    id: "docker-56",
    command: "docker compose up",
    description: "Démarrer tous les services du docker-compose.yml",
    example: "docker compose up -d",
    options: "-d (detached), --build (rebuild)",
    notes: "Crée les réseaux et volumes automatiquement",
    category: "Docker Compose",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-57",
    command: "docker compose up -d",
    description: "Démarrer les services en arrière-plan",
    example: "docker compose up -d --scale web=3",
    options: "--scale (nombre d'instances)",
    notes: "Mode production",
    category: "Docker Compose",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-58",
    command: "docker compose up --build",
    description: "Reconstruire les images avant de démarrer",
    example: "docker compose up --build -d",
    options: "--force-recreate",
    notes: "Utile après modification du Dockerfile",
    category: "Docker Compose",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "docker-59",
    command: "docker compose down",
    description: "Arrêter et supprimer les containers/réseaux",
    example: "docker compose down -v",
    options: "-v (supprimer volumes), --rmi all",
    notes: "Nettoie tout le stack",
    category: "Docker Compose",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-60",
    command: "docker compose ps",
    description: "Lister les containers du projet compose",
    example: "docker compose ps -a",
    options: "-a (tous)",
    notes: "Uniquement les services du fichier compose",
    category: "Docker Compose",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-61",
    command: "docker compose logs",
    description: "Afficher les logs de tous les services",
    example: "docker compose logs -f web",
    options: "-f (follow), --tail",
    notes: "Peut cibler un service spécifique",
    category: "Docker Compose",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-62",
    command: "docker compose exec <service> <cmd>",
    description: "Exécuter une commande dans un service",
    example: "docker compose exec web bash",
    options: "-T (sans TTY)",
    notes: "Équivalent de docker exec pour compose",
    category: "Docker Compose",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "docker-63",
    command: "docker compose build",
    description: "Construire ou reconstruire les services",
    example: "docker compose build --no-cache",
    options: "--no-cache, --pull",
    notes: "Sans démarrer les containers",
    category: "Docker Compose",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "docker-64",
    command: "docker compose pull",
    description: "Télécharger les images des services",
    example: "docker compose pull",
    options: "--ignore-pull-failures",
    notes: "Met à jour vers les dernières versions",
    category: "Docker Compose",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  {
    id: "docker-65",
    command: "docker compose restart",
    description: "Redémarrer les services",
    example: "docker compose restart web",
    options: "",
    notes: "Sans recréer les containers",
    category: "Docker Compose",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    id: "docker-66",
    command: "docker compose config",
    description: "Valider et afficher la configuration",
    example: "docker compose config --services",
    options: "--services, --volumes",
    notes: "Utile pour debug le fichier compose",
    category: "Docker Compose",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  {
    id: "docker-67",
    command: "docker compose -f <file> up",
    description: "Utiliser un fichier compose spécifique",
    example: "docker compose -f docker-compose.prod.yml up -d",
    options: "",
    notes: "Pour différents environnements",
    category: "Docker Compose",
    difficulty: "intermédiaire",
    isFavorite: true,
  },

  // ==================== REGISTRY ====================
  {
    id: "docker-68",
    command: "docker login",
    description: "Se connecter à un registry Docker",
    example: "docker login registry.example.com",
    options: "-u (username), -p (password)",
    notes: "Docker Hub par défaut",
    category: "Registry",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-69",
    command: "docker logout",
    description: "Se déconnecter d'un registry",
    example: "docker logout registry.example.com",
    options: "",
    notes: "Supprime les credentials stockés",
    category: "Registry",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    id: "docker-70",
    command: "docker push <image>",
    description: "Pousser une image vers un registry",
    example: "docker push myuser/myapp:v1.0",
    options: "",
    notes: "Nécessite d'être connecté au registry",
    category: "Registry",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "docker-71",
    command: "docker search <terme>",
    description: "Rechercher des images sur Docker Hub",
    example: "docker search nginx",
    options: "--filter stars=100",
    notes: "Recherche uniquement sur Docker Hub",
    category: "Registry",
    difficulty: "débutant",
    isFavorite: false,
  },

  // ==================== BUILD ====================
  {
    id: "docker-72",
    command: "docker build -t <tag> .",
    description: "Construire une image depuis un Dockerfile",
    example: "docker build -t myapp:latest .",
    options: "-f (Dockerfile), --no-cache",
    notes: "Le . indique le contexte de build",
    category: "Build",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "docker-73",
    command: "docker build -t <tag> -f <file> .",
    description: "Construire avec un Dockerfile spécifique",
    example: "docker build -t myapp -f Dockerfile.prod .",
    options: "",
    notes: "Pour différents environnements",
    category: "Build",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "docker-74",
    command: "docker build --no-cache -t <tag> .",
    description: "Construire sans utiliser le cache",
    example: "docker build --no-cache -t myapp:latest .",
    options: "",
    notes: "Plus lent mais garantit un build propre",
    category: "Build",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "docker-75",
    command: "docker build --build-arg <ARG>=<val> .",
    description: "Passer des arguments de build",
    example: "docker build --build-arg NODE_ENV=production -t myapp .",
    options: "",
    notes: "Variables utilisées pendant le build",
    category: "Build",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "docker-76",
    command: "docker build --target <stage> .",
    description: "Construire jusqu'à un stage spécifique (multi-stage)",
    example: "docker build --target builder -t myapp:builder .",
    options: "",
    notes: "Pour les Dockerfiles multi-stage",
    category: "Build",
    difficulty: "avancé",
    isFavorite: true,
  },
  {
    id: "docker-77",
    command: "docker buildx build --platform <platforms> .",
    description: "Build multi-architecture",
    example: "docker buildx build --platform linux/amd64,linux/arm64 -t myapp .",
    options: "--push (push direct)",
    notes: "Pour supporter différentes architectures",
    category: "Build",
    difficulty: "avancé",
    isFavorite: false,
  },

  // ==================== SYSTEM ====================
  {
    id: "docker-78",
    command: "docker system df",
    description: "Afficher l'utilisation disque de Docker",
    example: "docker system df -v",
    options: "-v (verbose)",
    notes: "Images, containers, volumes, build cache",
    category: "System",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "docker-79",
    command: "docker system prune",
    description: "Nettoyer tout ce qui n'est pas utilisé",
    example: "docker system prune -a -f",
    options: "-a (toutes images), -f (sans confirmation), --volumes",
    notes: "ATTENTION: Supprime beaucoup de choses",
    category: "System",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "docker-80",
    command: "docker system prune -a --volumes",
    description: "Nettoyage complet (images, containers, volumes)",
    example: "docker system prune -a --volumes -f",
    options: "",
    notes: "Reset complet de Docker - ATTENTION aux données",
    category: "System",
    difficulty: "avancé",
    isFavorite: true,
  },
  {
    id: "docker-81",
    command: "docker info",
    description: "Afficher les informations système Docker",
    example: "docker info",
    options: "",
    notes: "Version, driver, ressources, etc.",
    category: "System",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    id: "docker-82",
    command: "docker version",
    description: "Afficher la version de Docker",
    example: "docker version",
    options: "--format",
    notes: "Client et Server (daemon)",
    category: "System",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    id: "docker-83",
    command: "docker events",
    description: "Afficher les événements Docker en temps réel",
    example: "docker events --filter 'type=container'",
    options: "--filter, --since, --until",
    notes: "Pour le monitoring et debug",
    category: "System",
    difficulty: "avancé",
    isFavorite: false,
  },

  // ==================== AVANCÉ ====================
  {
    id: "docker-84",
    command: "docker commit <container> <image>",
    description: "Créer une image à partir d'un container modifié",
    example: "docker commit my-container myimage:v1",
    options: "-m (message), -a (author)",
    notes: "Non recommandé - préférer Dockerfile",
    category: "Avancé",
    difficulty: "avancé",
    isFavorite: false,
  },
  {
    id: "docker-85",
    command: "docker export <container> > file.tar",
    description: "Exporter le filesystem d'un container",
    example: "docker export my-container > backup.tar",
    options: "",
    notes: "Sans les layers et métadonnées",
    category: "Avancé",
    difficulty: "avancé",
    isFavorite: false,
  },
  {
    id: "docker-86",
    command: "docker import <file.tar> <image>",
    description: "Créer une image depuis un tar export",
    example: "docker import backup.tar myimage:restored",
    options: "",
    notes: "Image sans historique",
    category: "Avancé",
    difficulty: "avancé",
    isFavorite: false,
  },
  {
    id: "docker-87",
    command: "docker update --restart=always <container>",
    description: "Modifier la config d'un container en cours",
    example: "docker update --memory=1g my-container",
    options: "--memory, --cpus, --restart",
    notes: "Limité aux options de ressources",
    category: "Avancé",
    difficulty: "avancé",
    isFavorite: false,
  },
  {
    id: "docker-88",
    command: "docker wait <container>",
    description: "Attendre qu'un container s'arrête et retourner le code",
    example: "docker wait my-container",
    options: "",
    notes: "Utile dans les scripts",
    category: "Avancé",
    difficulty: "avancé",
    isFavorite: false,
  },
  {
    id: "docker-89",
    command: "docker attach <container>",
    description: "Attacher le terminal à un container en cours",
    example: "docker attach my-container",
    options: "--no-stdin, --sig-proxy=false",
    notes: "Ctrl+P Ctrl+Q pour détacher sans arrêter",
    category: "Avancé",
    difficulty: "avancé",
    isFavorite: false,
  },
  {
    id: "docker-90",
    command: "docker pause <container>",
    description: "Mettre en pause un container (freeze)",
    example: "docker pause my-container",
    options: "",
    notes: "Les processus sont gelés, pas arrêtés",
    category: "Avancé",
    difficulty: "avancé",
    isFavorite: false,
  },
  {
    id: "docker-91",
    command: "docker unpause <container>",
    description: "Reprendre un container en pause",
    example: "docker unpause my-container",
    options: "",
    notes: "Les processus reprennent où ils en étaient",
    category: "Avancé",
    difficulty: "avancé",
    isFavorite: false,
  },
];
