export type DifficultyLevel = "débutant" | "intermédiaire" | "avancé";

export interface GitCommand {
  id: string;
  command: string;
  description: string;
  example: string;
  options: string;
  notes: string;
  category: string;
  difficulty: DifficultyLevel;
  isFavorite: boolean;
}

export const defaultGitCategories = [
  "Configuration",
  "Initialisation",
  "Staging",
  "Commits",
  "Branches",
  "Merge & Rebase",
  "Remote",
  "Historique",
  "Annulation",
  "Stash",
  "Tags",
  "Avancé",
];

export const difficultyColors: Record<DifficultyLevel, { bg: string; text: string }> = {
  débutant: { bg: "bg-emerald-500/10", text: "text-emerald-400" },
  intermédiaire: { bg: "bg-amber-500/10", text: "text-amber-400" },
  avancé: { bg: "bg-rose-500/10", text: "text-rose-400" },
};

export const defaultGitCommands: GitCommand[] = [
  // ==================== CONFIGURATION ====================
  {
    id: "git-1",
    command: "git config --global user.name \"Nom\"",
    description: "Définir le nom d'utilisateur global pour tous les dépôts",
    example: "git config --global user.name \"John Doe\"",
    options: "--local (dépôt actuel), --system (système)",
    notes: "Configuration stockée dans ~/.gitconfig",
    category: "Configuration",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    id: "git-2",
    command: "git config --global user.email \"email\"",
    description: "Définir l'email global pour tous les dépôts",
    example: "git config --global user.email \"john@example.com\"",
    options: "--local, --system",
    notes: "Utilisé pour identifier l'auteur des commits",
    category: "Configuration",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    id: "git-3",
    command: "git config --list",
    description: "Afficher toutes les configurations Git",
    example: "git config --list --show-origin",
    options: "--show-origin (affiche le fichier source)",
    notes: "Utile pour débugger les problèmes de config",
    category: "Configuration",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    id: "git-4",
    command: "git config --global core.editor \"code --wait\"",
    description: "Définir VS Code comme éditeur par défaut",
    example: "git config --global core.editor \"vim\"",
    options: "vim, nano, code --wait, subl -n -w",
    notes: "Utilisé pour les messages de commit et rebase interactif",
    category: "Configuration",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  {
    id: "git-5",
    command: "git config --global alias.co checkout",
    description: "Créer un alias pour une commande Git",
    example: "git config --global alias.st status",
    options: "alias.br branch, alias.ci commit",
    notes: "Gain de temps avec des raccourcis personnalisés",
    category: "Configuration",
    difficulty: "intermédiaire",
    isFavorite: true,
  },

  // ==================== INITIALISATION ====================
  {
    id: "git-6",
    command: "git init",
    description: "Initialiser un nouveau dépôt Git dans le dossier actuel",
    example: "git init mon-projet",
    options: "--bare (dépôt nu sans working directory)",
    notes: "Crée un dossier .git avec l'historique",
    category: "Initialisation",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-7",
    command: "git clone <url>",
    description: "Cloner un dépôt distant en local",
    example: "git clone https://github.com/user/repo.git",
    options: "--depth 1 (shallow clone), --branch <name>",
    notes: "Clone automatiquement toutes les branches",
    category: "Initialisation",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-8",
    command: "git clone --depth 1 <url>",
    description: "Clone superficiel avec uniquement le dernier commit",
    example: "git clone --depth 1 https://github.com/user/repo.git",
    options: "--single-branch (une seule branche)",
    notes: "Idéal pour les gros dépôts ou CI/CD",
    category: "Initialisation",
    difficulty: "intermédiaire",
    isFavorite: false,
  },

  // ==================== STAGING ====================
  {
    id: "git-9",
    command: "git status",
    description: "Afficher l'état du working directory et staging area",
    example: "git status -s",
    options: "-s (format court), -b (affiche la branche)",
    notes: "Commande de base pour voir les changements",
    category: "Staging",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-10",
    command: "git add <fichier>",
    description: "Ajouter un fichier à la staging area",
    example: "git add index.html",
    options: "-A (tous), -p (par morceaux), -u (modifiés)",
    notes: "Prépare les fichiers pour le commit",
    category: "Staging",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-11",
    command: "git add .",
    description: "Ajouter tous les fichiers modifiés à la staging area",
    example: "git add .",
    options: "-A (inclut les suppressions)",
    notes: "Attention aux fichiers non désirés",
    category: "Staging",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-12",
    command: "git add -p",
    description: "Ajouter des modifications de façon interactive par morceaux",
    example: "git add -p index.js",
    options: "y (oui), n (non), s (split), e (edit)",
    notes: "Permet des commits plus granulaires",
    category: "Staging",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "git-13",
    command: "git reset HEAD <fichier>",
    description: "Retirer un fichier de la staging area",
    example: "git reset HEAD style.css",
    options: "--soft, --hard, --mixed",
    notes: "Ne supprime pas les modifications locales",
    category: "Staging",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    id: "git-14",
    command: "git diff",
    description: "Afficher les différences non staged",
    example: "git diff --stat",
    options: "--staged (staged), --name-only (noms)",
    notes: "Compare working directory et staging",
    category: "Staging",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    id: "git-15",
    command: "git diff --staged",
    description: "Afficher les différences staged (prêtes à commiter)",
    example: "git diff --staged --name-status",
    options: "--cached (synonyme)",
    notes: "Vérifie ce qui sera inclus dans le prochain commit",
    category: "Staging",
    difficulty: "débutant",
    isFavorite: false,
  },

  // ==================== COMMITS ====================
  {
    id: "git-16",
    command: "git commit -m \"message\"",
    description: "Créer un commit avec un message",
    example: "git commit -m \"feat: add login page\"",
    options: "-a (auto-stage modifiés), --amend",
    notes: "Utiliser des messages descriptifs (conventional commits)",
    category: "Commits",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-17",
    command: "git commit -am \"message\"",
    description: "Stage et commit en une seule commande",
    example: "git commit -am \"fix: typo in readme\"",
    options: "Ne fonctionne que pour fichiers trackés",
    notes: "Raccourci pour add + commit",
    category: "Commits",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-18",
    command: "git commit --amend",
    description: "Modifier le dernier commit (message ou contenu)",
    example: "git commit --amend -m \"nouveau message\"",
    options: "--no-edit (garder le message)",
    notes: "Ne pas utiliser sur commits déjà pushés",
    category: "Commits",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "git-19",
    command: "git commit --amend --no-edit",
    description: "Ajouter des fichiers au dernier commit sans changer le message",
    example: "git add oubli.js && git commit --amend --no-edit",
    options: "",
    notes: "Pratique pour ajouter des fichiers oubliés",
    category: "Commits",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "git-20",
    command: "git commit --allow-empty -m \"message\"",
    description: "Créer un commit vide (utile pour déclencher CI)",
    example: "git commit --allow-empty -m \"trigger: rebuild\"",
    options: "",
    notes: "Utilisé pour relancer des pipelines CI/CD",
    category: "Commits",
    difficulty: "avancé",
    isFavorite: false,
  },

  // ==================== BRANCHES ====================
  {
    id: "git-21",
    command: "git branch",
    description: "Lister toutes les branches locales",
    example: "git branch -a",
    options: "-a (toutes), -r (remote), -v (verbose)",
    notes: "La branche actuelle est marquée avec *",
    category: "Branches",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-22",
    command: "git branch <nom>",
    description: "Créer une nouvelle branche",
    example: "git branch feature/login",
    options: "-d (supprimer), -D (forcer suppression)",
    notes: "Ne switch pas automatiquement sur la nouvelle branche",
    category: "Branches",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    id: "git-23",
    command: "git checkout <branche>",
    description: "Basculer vers une branche existante",
    example: "git checkout develop",
    options: "-b (créer et switch)",
    notes: "Utiliser git switch pour une syntaxe moderne",
    category: "Branches",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-24",
    command: "git checkout -b <branche>",
    description: "Créer une nouvelle branche et y basculer",
    example: "git checkout -b feature/payment",
    options: "",
    notes: "Équivalent à git branch + git checkout",
    category: "Branches",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-25",
    command: "git switch <branche>",
    description: "Basculer vers une branche (syntaxe moderne)",
    example: "git switch main",
    options: "-c (créer), -d (detached HEAD)",
    notes: "Alternative moderne à git checkout",
    category: "Branches",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-26",
    command: "git switch -c <branche>",
    description: "Créer et basculer vers une nouvelle branche",
    example: "git switch -c feature/auth",
    options: "",
    notes: "Syntaxe moderne pour créer une branche",
    category: "Branches",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-27",
    command: "git branch -d <branche>",
    description: "Supprimer une branche locale (merged)",
    example: "git branch -d feature/old",
    options: "-D (forcer même si non merged)",
    notes: "Impossible de supprimer la branche courante",
    category: "Branches",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    id: "git-28",
    command: "git branch -m <ancien> <nouveau>",
    description: "Renommer une branche",
    example: "git branch -m old-name new-name",
    options: "-M (forcer)",
    notes: "Si sur la branche: git branch -m nouveau-nom",
    category: "Branches",
    difficulty: "intermédiaire",
    isFavorite: false,
  },

  // ==================== MERGE & REBASE ====================
  {
    id: "git-29",
    command: "git merge <branche>",
    description: "Fusionner une branche dans la branche courante",
    example: "git merge feature/login",
    options: "--no-ff (force commit de merge), --squash",
    notes: "Crée un commit de merge si non fast-forward",
    category: "Merge & Rebase",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-30",
    command: "git merge --no-ff <branche>",
    description: "Fusionner en forçant un commit de merge",
    example: "git merge --no-ff feature/auth",
    options: "",
    notes: "Préserve l'historique de la feature branch",
    category: "Merge & Rebase",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "git-31",
    command: "git merge --squash <branche>",
    description: "Fusionner en écrasant tous les commits en un seul",
    example: "git merge --squash feature/cleanup",
    options: "",
    notes: "Nécessite un commit manuel après",
    category: "Merge & Rebase",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "git-32",
    command: "git rebase <branche>",
    description: "Rebaser la branche courante sur une autre",
    example: "git rebase main",
    options: "-i (interactif), --onto",
    notes: "Ne jamais rebaser des commits publics",
    category: "Merge & Rebase",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "git-33",
    command: "git rebase -i HEAD~<n>",
    description: "Rebase interactif pour modifier les n derniers commits",
    example: "git rebase -i HEAD~3",
    options: "pick, squash, fixup, reword, edit, drop",
    notes: "Puissant pour nettoyer l'historique",
    category: "Merge & Rebase",
    difficulty: "avancé",
    isFavorite: true,
  },
  {
    id: "git-34",
    command: "git rebase --abort",
    description: "Annuler un rebase en cours",
    example: "git rebase --abort",
    options: "--continue, --skip",
    notes: "Revient à l'état avant le rebase",
    category: "Merge & Rebase",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  {
    id: "git-35",
    command: "git cherry-pick <commit>",
    description: "Appliquer un commit spécifique sur la branche courante",
    example: "git cherry-pick abc1234",
    options: "-n (sans commit), -x (référence)",
    notes: "Utile pour récupérer un fix spécifique",
    category: "Merge & Rebase",
    difficulty: "avancé",
    isFavorite: true,
  },

  // ==================== REMOTE ====================
  {
    id: "git-36",
    command: "git remote -v",
    description: "Lister les dépôts distants configurés",
    example: "git remote -v",
    options: "add, remove, rename, set-url",
    notes: "Affiche les URLs fetch et push",
    category: "Remote",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-37",
    command: "git remote add <nom> <url>",
    description: "Ajouter un nouveau dépôt distant",
    example: "git remote add origin https://github.com/user/repo.git",
    options: "",
    notes: "origin est le nom conventionnel pour le remote principal",
    category: "Remote",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-38",
    command: "git fetch",
    description: "Télécharger les changements du remote sans merger",
    example: "git fetch origin",
    options: "--all (tous les remotes), --prune",
    notes: "Met à jour les références remote locales",
    category: "Remote",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-39",
    command: "git fetch --prune",
    description: "Fetch et supprimer les références de branches supprimées sur remote",
    example: "git fetch --prune origin",
    options: "-p (raccourci)",
    notes: "Nettoie les branches remote obsolètes",
    category: "Remote",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "git-40",
    command: "git pull",
    description: "Fetch et merge les changements du remote",
    example: "git pull origin main",
    options: "--rebase (rebase au lieu de merge)",
    notes: "Équivalent à fetch + merge",
    category: "Remote",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-41",
    command: "git pull --rebase",
    description: "Pull en rebasant au lieu de merger",
    example: "git pull --rebase origin main",
    options: "",
    notes: "Historique plus linéaire",
    category: "Remote",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "git-42",
    command: "git push",
    description: "Envoyer les commits locaux vers le remote",
    example: "git push origin main",
    options: "-u (set upstream), -f (forcer)",
    notes: "Nécessite les droits d'écriture sur le remote",
    category: "Remote",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-43",
    command: "git push -u origin <branche>",
    description: "Push et définir la branche upstream",
    example: "git push -u origin feature/new",
    options: "--set-upstream",
    notes: "Permet ensuite de faire git push sans arguments",
    category: "Remote",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-44",
    command: "git push --force-with-lease",
    description: "Force push sécurisé (vérifie les changements remote)",
    example: "git push --force-with-lease origin feature",
    options: "",
    notes: "Plus sûr que --force, vérifie que personne n'a pushé",
    category: "Remote",
    difficulty: "avancé",
    isFavorite: true,
  },
  {
    id: "git-45",
    command: "git push origin --delete <branche>",
    description: "Supprimer une branche sur le remote",
    example: "git push origin --delete feature/old",
    options: "",
    notes: "Nettoyer les branches après merge",
    category: "Remote",
    difficulty: "intermédiaire",
    isFavorite: false,
  },

  // ==================== HISTORIQUE ====================
  {
    id: "git-46",
    command: "git log",
    description: "Afficher l'historique des commits",
    example: "git log --oneline",
    options: "--oneline, --graph, --all, -n <nombre>",
    notes: "Appuyer q pour quitter",
    category: "Historique",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-47",
    command: "git log --oneline --graph --all",
    description: "Afficher un graphe compact de tout l'historique",
    example: "git log --oneline --graph --all --decorate",
    options: "--decorate (montre les refs)",
    notes: "Visualisation claire des branches",
    category: "Historique",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-48",
    command: "git log -p <fichier>",
    description: "Afficher l'historique avec les diffs d'un fichier",
    example: "git log -p src/App.js",
    options: "--follow (suit les renommages)",
    notes: "Utile pour comprendre l'évolution d'un fichier",
    category: "Historique",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  {
    id: "git-49",
    command: "git log --author=\"<nom>\"",
    description: "Filtrer les commits par auteur",
    example: "git log --author=\"John\"",
    options: "--since, --until, --grep",
    notes: "Peut utiliser une partie du nom",
    category: "Historique",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  {
    id: "git-50",
    command: "git show <commit>",
    description: "Afficher les détails d'un commit spécifique",
    example: "git show abc1234",
    options: "--stat (résumé des fichiers)",
    notes: "Montre le diff complet du commit",
    category: "Historique",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    id: "git-51",
    command: "git blame <fichier>",
    description: "Afficher qui a modifié chaque ligne d'un fichier",
    example: "git blame src/index.js",
    options: "-L <start>,<end> (lignes spécifiques)",
    notes: "Utile pour comprendre l'origine d'un bug",
    category: "Historique",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "git-52",
    command: "git reflog",
    description: "Afficher l'historique des références HEAD",
    example: "git reflog",
    options: "--all (toutes les refs)",
    notes: "Sauveur pour récupérer des commits perdus",
    category: "Historique",
    difficulty: "avancé",
    isFavorite: true,
  },

  // ==================== ANNULATION ====================
  {
    id: "git-53",
    command: "git checkout -- <fichier>",
    description: "Annuler les modifications non staged d'un fichier",
    example: "git checkout -- index.html",
    options: "",
    notes: "Restaure la version du dernier commit",
    category: "Annulation",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-54",
    command: "git restore <fichier>",
    description: "Restaurer un fichier (syntaxe moderne)",
    example: "git restore style.css",
    options: "--staged (unstage), --source=<commit>",
    notes: "Alternative moderne à checkout --",
    category: "Annulation",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-55",
    command: "git restore --staged <fichier>",
    description: "Retirer un fichier de la staging area",
    example: "git restore --staged app.js",
    options: "",
    notes: "Équivalent à git reset HEAD <fichier>",
    category: "Annulation",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-56",
    command: "git reset --soft HEAD~1",
    description: "Annuler le dernier commit en gardant les changements staged",
    example: "git reset --soft HEAD~1",
    options: "",
    notes: "Utile pour refaire un commit",
    category: "Annulation",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "git-57",
    command: "git reset --mixed HEAD~1",
    description: "Annuler le dernier commit, garder les changements unstaged",
    example: "git reset HEAD~1",
    options: "--mixed est le défaut",
    notes: "Les fichiers reviennent en working directory",
    category: "Annulation",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "git-58",
    command: "git reset --hard HEAD~1",
    description: "Annuler le dernier commit et supprimer tous les changements",
    example: "git reset --hard HEAD~3",
    options: "",
    notes: "DANGER: Perte de données irréversible",
    category: "Annulation",
    difficulty: "avancé",
    isFavorite: true,
  },
  {
    id: "git-59",
    command: "git revert <commit>",
    description: "Créer un commit qui annule un commit précédent",
    example: "git revert abc1234",
    options: "-n (sans commit auto), --no-edit",
    notes: "Sûr pour les commits déjà pushés",
    category: "Annulation",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    id: "git-60",
    command: "git clean -fd",
    description: "Supprimer les fichiers non trackés",
    example: "git clean -fdn (dry-run d'abord)",
    options: "-n (dry-run), -x (inclut ignorés)",
    notes: "Toujours faire un dry-run d'abord !",
    category: "Annulation",
    difficulty: "avancé",
    isFavorite: false,
  },

  // ==================== STASH ====================
  {
    id: "git-61",
    command: "git stash",
    description: "Mettre de côté les changements en cours",
    example: "git stash",
    options: "-u (inclut untracked), -a (inclut ignorés)",
    notes: "Utile pour changer de branche rapidement",
    category: "Stash",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-62",
    command: "git stash push -m \"message\"",
    description: "Stash avec un message descriptif",
    example: "git stash push -m \"WIP: login form\"",
    options: "",
    notes: "Facilite l'identification des stashes",
    category: "Stash",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-63",
    command: "git stash list",
    description: "Lister tous les stashes",
    example: "git stash list",
    options: "",
    notes: "Les stashes sont numérotés (stash@{0}, etc.)",
    category: "Stash",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    id: "git-64",
    command: "git stash pop",
    description: "Appliquer et supprimer le dernier stash",
    example: "git stash pop stash@{2}",
    options: "",
    notes: "Restaure les changements et supprime le stash",
    category: "Stash",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-65",
    command: "git stash apply",
    description: "Appliquer un stash sans le supprimer",
    example: "git stash apply stash@{1}",
    options: "",
    notes: "Le stash reste dans la liste",
    category: "Stash",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    id: "git-66",
    command: "git stash drop",
    description: "Supprimer un stash spécifique",
    example: "git stash drop stash@{0}",
    options: "",
    notes: "Supprime sans appliquer",
    category: "Stash",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    id: "git-67",
    command: "git stash clear",
    description: "Supprimer tous les stashes",
    example: "git stash clear",
    options: "",
    notes: "Attention: action irréversible",
    category: "Stash",
    difficulty: "intermédiaire",
    isFavorite: false,
  },

  // ==================== TAGS ====================
  {
    id: "git-68",
    command: "git tag",
    description: "Lister tous les tags",
    example: "git tag -l \"v1.*\"",
    options: "-l (filter pattern)",
    notes: "Les tags marquent des versions/releases",
    category: "Tags",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    id: "git-69",
    command: "git tag <nom>",
    description: "Créer un tag léger",
    example: "git tag v1.0.0",
    options: "",
    notes: "Juste un pointeur vers un commit",
    category: "Tags",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-70",
    command: "git tag -a <nom> -m \"message\"",
    description: "Créer un tag annoté avec message",
    example: "git tag -a v1.0.0 -m \"Version 1.0.0\"",
    options: "-a (annoté), -m (message)",
    notes: "Recommandé pour les releases",
    category: "Tags",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-71",
    command: "git push origin <tag>",
    description: "Pousser un tag vers le remote",
    example: "git push origin v1.0.0",
    options: "--tags (tous les tags)",
    notes: "Les tags ne sont pas pushés par défaut",
    category: "Tags",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    id: "git-72",
    command: "git push origin --tags",
    description: "Pousser tous les tags vers le remote",
    example: "git push origin --tags",
    options: "",
    notes: "Push tous les tags locaux",
    category: "Tags",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    id: "git-73",
    command: "git tag -d <nom>",
    description: "Supprimer un tag local",
    example: "git tag -d v1.0.0",
    options: "",
    notes: "Ne supprime pas le tag remote",
    category: "Tags",
    difficulty: "intermédiaire",
    isFavorite: false,
  },

  // ==================== AVANCÉ ====================
  {
    id: "git-74",
    command: "git bisect start",
    description: "Démarrer une recherche binaire pour trouver un bug",
    example: "git bisect start HEAD v1.0.0",
    options: "good, bad, reset",
    notes: "Trouve le commit qui a introduit un bug",
    category: "Avancé",
    difficulty: "avancé",
    isFavorite: true,
  },
  {
    id: "git-75",
    command: "git worktree add <path> <branche>",
    description: "Créer un nouveau working tree pour une branche",
    example: "git worktree add ../hotfix hotfix/urgent",
    options: "list, remove, prune",
    notes: "Travailler sur plusieurs branches simultanément",
    category: "Avancé",
    difficulty: "avancé",
    isFavorite: false,
  },
  {
    id: "git-76",
    command: "git submodule add <url>",
    description: "Ajouter un sous-module Git",
    example: "git submodule add https://github.com/lib/util.git libs/util",
    options: "update, init, status",
    notes: "Pour inclure des dépôts externes",
    category: "Avancé",
    difficulty: "avancé",
    isFavorite: false,
  },
  {
    id: "git-77",
    command: "git log --pretty=format:\"%h %s\"",
    description: "Format personnalisé pour git log",
    example: "git log --pretty=format:\"%h - %an: %s\"",
    options: "%H (hash), %an (author), %s (subject)",
    notes: "Très flexible pour scripts et rapports",
    category: "Avancé",
    difficulty: "avancé",
    isFavorite: false,
  },
  {
    id: "git-78",
    command: "git rev-parse HEAD",
    description: "Obtenir le hash complet du commit actuel",
    example: "git rev-parse --short HEAD",
    options: "--short (hash court)",
    notes: "Utile dans les scripts",
    category: "Avancé",
    difficulty: "avancé",
    isFavorite: false,
  },
  {
    id: "git-79",
    command: "git gc",
    description: "Nettoyer et optimiser le dépôt",
    example: "git gc --aggressive",
    options: "--aggressive (nettoyage approfondi)",
    notes: "Réduit la taille du dépôt",
    category: "Avancé",
    difficulty: "avancé",
    isFavorite: false,
  },
  {
    id: "git-80",
    command: "git archive -o <fichier.zip> HEAD",
    description: "Créer une archive du dépôt",
    example: "git archive -o projet.zip HEAD",
    options: "--format=tar, --prefix=dossier/",
    notes: "Export sans l'historique Git",
    category: "Avancé",
    difficulty: "avancé",
    isFavorite: false,
  },
];
