export type DifficultyLevel = "débutant" | "intermédiaire" | "avancé";

export interface WPCLICommand {
  id: string;
  command: string;
  description: string;
  example: string;
  options: string;
  notes: string;
  category: string;
  difficulty: DifficultyLevel;
  isFavorite: boolean;
  createdAt: string;
  updatedAt: string;
}

export const defaultCategories = [
  "Core",
  "Plugins",
  "Themes",
  "Database",
  "Users",
  "Posts",
  "Cache",
  "Config",
  "Media",
  "Maintenance",
  "WooCommerce",
];

export const difficultyColors: Record<DifficultyLevel, { bg: string; text: string }> = {
  "débutant": { bg: "bg-emerald-500/20", text: "text-emerald-400" },
  "intermédiaire": { bg: "bg-amber-500/20", text: "text-amber-400" },
  "avancé": { bg: "bg-rose-500/20", text: "text-rose-400" },
};

export const defaultCommands: Omit<WPCLICommand, "id" | "createdAt" | "updatedAt">[] = [
  // Core
  {
    command: "wp core version",
    description: "Affiche la version de WordPress installée",
    example: "wp core version\n# Output: 6.4.2",
    options: "--extra : Affiche des infos supplémentaires",
    notes: "Utile pour vérifier rapidement la version en production",
    category: "Core",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    command: "wp core update",
    description: "Met à jour WordPress vers la dernière version",
    example: "wp core update --version=6.4.2",
    options: "--version=<version> : Version spécifique\n--force : Forcer la réinstallation\n--minor : Mise à jour mineure uniquement",
    notes: "Toujours faire un backup avant de mettre à jour",
    category: "Core",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    command: "wp core download",
    description: "Télécharge les fichiers WordPress",
    example: "wp core download --locale=fr_FR",
    options: "--locale=<locale> : Langue\n--version=<version> : Version spécifique\n--skip-content : Sans wp-content",
    notes: "Premier pas pour une installation WordPress",
    category: "Core",
    difficulty: "débutant",
    isFavorite: false,
  },
  // Plugins
  {
    command: "wp plugin list",
    description: "Liste tous les plugins installés",
    example: "wp plugin list --status=active --format=table",
    options: "--status=<status> : active, inactive, must-use\n--format=<format> : table, csv, json",
    notes: "Parfait pour auditer les plugins d'un site",
    category: "Plugins",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    command: "wp plugin install",
    description: "Installe un plugin depuis le répertoire WordPress",
    example: "wp plugin install advanced-custom-fields --activate",
    options: "--activate : Active après installation\n--version=<version> : Version spécifique\n--force : Réinstalle si déjà présent",
    notes: "Accepte aussi une URL ZIP ou un chemin local",
    category: "Plugins",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    command: "wp plugin update --all",
    description: "Met à jour tous les plugins",
    example: "wp plugin update --all --dry-run",
    options: "--all : Tous les plugins\n--dry-run : Simule sans appliquer\n--exclude=<plugins> : Exclure certains plugins",
    notes: "Toujours tester en staging d'abord",
    category: "Plugins",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  // Database
  {
    command: "wp db export",
    description: "Exporte la base de données en fichier SQL",
    example: "wp db export backup-$(date +%Y%m%d).sql --add-drop-table",
    options: "--add-drop-table : Ajoute DROP TABLE\n--tables=<tables> : Tables spécifiques\n--exclude_tables=<tables> : Exclure des tables",
    notes: "Indispensable avant toute manipulation risquée",
    category: "Database",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    command: "wp db import",
    description: "Importe un fichier SQL dans la base de données",
    example: "wp db import backup.sql",
    options: "Aucune option majeure, juste le fichier en argument",
    notes: "Écrase les données existantes, attention !",
    category: "Database",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  {
    command: "wp search-replace",
    description: "Recherche et remplace du texte dans la BDD",
    example: "wp search-replace 'http://old.com' 'https://new.com' --dry-run",
    options: "--dry-run : Simule\n--network : Multisite\n--all-tables : Toutes les tables\n--precise : Gère la sérialisation",
    notes: "Essentiel pour les migrations de domaine",
    category: "Database",
    difficulty: "avancé",
    isFavorite: true,
  },
  // Users
  {
    command: "wp user list",
    description: "Liste tous les utilisateurs",
    example: "wp user list --role=administrator --format=table",
    options: "--role=<role> : Filtrer par rôle\n--format=<format> : table, csv, json, ids",
    notes: "Utile pour auditer les comptes admin",
    category: "Users",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    command: "wp user create",
    description: "Crée un nouvel utilisateur",
    example: "wp user create john john@example.com --role=editor --user_pass=secret123",
    options: "--role=<role> : Rôle assigné\n--user_pass=<pass> : Mot de passe\n--send-email : Envoie le mail de bienvenue",
    notes: "Le premier argument est le login, le second l'email",
    category: "Users",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    command: "wp user update",
    description: "Met à jour un utilisateur existant",
    example: "wp user update 1 --user_pass=newpassword --skip-email",
    options: "--user_pass=<pass> : Nouveau mot de passe\n--role=<role> : Changer le rôle\n--skip-email : Ne pas notifier",
    notes: "Accepte l'ID, le login ou l'email comme identifiant",
    category: "Users",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  // Cache
  {
    command: "wp cache flush",
    description: "Vide le cache objet WordPress",
    example: "wp cache flush",
    options: "Aucune option",
    notes: "Pour le cache persistant (Redis, Memcached)",
    category: "Cache",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    command: "wp transient delete --all",
    description: "Supprime tous les transients",
    example: "wp transient delete --all --network",
    options: "--all : Tous les transients\n--network : Multisite\n--expired : Seulement les expirés",
    notes: "Nettoie les données temporaires périmées",
    category: "Cache",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  // Config
  {
    command: "wp config get",
    description: "Affiche une valeur de wp-config.php",
    example: "wp config get DB_NAME",
    options: "--type=<type> : constant ou variable\n--format=<format> : Format de sortie",
    notes: "Lecture sûre des constantes de configuration",
    category: "Config",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    command: "wp config set",
    description: "Modifie une valeur dans wp-config.php",
    example: "wp config set WP_DEBUG true --raw",
    options: "--raw : Valeur brute (true, false, entiers)\n--type=<type> : constant ou variable\n--add : Ajoute si n'existe pas",
    notes: "Modifier les constantes sans éditer le fichier",
    category: "Config",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  // Maintenance
  {
    command: "wp cron event list",
    description: "Liste les tâches cron programmées",
    example: "wp cron event list --format=table",
    options: "--format=<format> : table, csv, json",
    notes: "Diagnostiquer les problèmes de cron",
    category: "Maintenance",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  {
    command: "wp rewrite flush",
    description: "Régénère les règles de réécriture",
    example: "wp rewrite flush --hard",
    options: "--hard : Réécrit aussi .htaccess",
    notes: "Résout souvent les erreurs 404 sur les permaliens",
    category: "Maintenance",
    difficulty: "débutant",
    isFavorite: true,
  },
  // WooCommerce - Gestion des Stocks
  {
    command: "wp wc product update <id> --stock_quantity=<qty>",
    description: "Met à jour la quantité en stock d'un produit",
    example: "wp wc product update 123 --stock_quantity=50",
    options: "--stock_quantity=<qty> : Nouvelle quantité en stock\n--manage_stock=true : Active la gestion des stocks si nécessaire",
    notes: "Nécessite le package wp-cli-woocommerce. Modifie directement le stock, attention aux commandes en cours !",
    category: "WooCommerce",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    command: "wp wc product update <id> --manage_stock=true",
    description: "Active la gestion automatique des stocks pour un produit",
    example: "wp wc product update 123 --manage_stock=true",
    options: "--manage_stock=true : Active la gestion\n--manage_stock=false : Désactive la gestion",
    notes: "Permet à WooCommerce de gérer automatiquement les stocks pour ce produit",
    category: "WooCommerce",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    command: "wp wc product update <id> --stock_status=instock",
    description: "Définit le statut du stock d'un produit",
    example: "wp wc product update 123 --stock_status=instock",
    options: "--stock_status=instock : En stock\n--stock_status=outofstock : Rupture de stock\n--stock_status=onbackorder : En réapprovisionnement",
    notes: "Change le statut d'affichage du produit sur le site",
    category: "WooCommerce",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    command: "wp wc product list --stock_status=outofstock",
    description: "Liste tous les produits en rupture de stock",
    example: "wp wc product list --stock_status=outofstock --format=table",
    options: "--stock_status=<status> : instock, outofstock, onbackorder\n--format=<format> : table, csv, json\n--fields=<fields> : Champs à afficher",
    notes: "Utile pour identifier rapidement les produits à réapprovisionner",
    category: "WooCommerce",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    command: "wp wc product list --low_in_stock=true",
    description: "Liste les produits avec un stock faible",
    example: "wp wc product list --low_in_stock=true --format=table",
    options: "--low_in_stock=true : Stock faible uniquement\n--format=<format> : table, csv, json\n--fields=id,name,stock_quantity : Champs spécifiques",
    notes: "Aide à prévenir les ruptures de stock en identifiant les produits à réapprovisionner",
    category: "WooCommerce",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    command: "wp wc product list --fields=id,name,stock_quantity,stock_status",
    description: "Affiche les produits avec leurs informations de stock",
    example: "wp wc product list --fields=id,name,stock_quantity,stock_status --format=table",
    options: "--fields=<fields> : Liste des champs séparés par des virgules\n--format=<format> : table, csv, json\n--per_page=<n> : Nombre de résultats",
    notes: "Vue d'ensemble rapide de tous les stocks",
    category: "WooCommerce",
    difficulty: "débutant",
    isFavorite: false,
  },
  // WooCommerce - Gestion des Produits
  {
    command: "wp wc product list",
    description: "Liste tous les produits WooCommerce",
    example: "wp wc product list --format=table --per_page=20",
    options: "--format=<format> : table, csv, json\n--per_page=<n> : Nombre de résultats\n--fields=<fields> : Champs à afficher\n--status=<status> : draft, pending, private, publish",
    notes: "Nécessite le package wp-cli-woocommerce installé via 'wp package install automattic/wp-cli-woocommerce'",
    category: "WooCommerce",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    command: "wp wc product get <id>",
    description: "Obtenir les détails complets d'un produit",
    example: "wp wc product get 123 --format=json",
    options: "--format=<format> : table, json, yaml\n--fields=<fields> : Champs spécifiques à afficher",
    notes: "Affiche toutes les informations du produit (prix, stock, catégories, etc.)",
    category: "WooCommerce",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    command: "wp wc product create",
    description: "Crée un nouveau produit WooCommerce",
    example: "wp wc product create --name='Nouveau produit' --type=simple --regular_price=29.99 --stock_quantity=10",
    options: "--name=<name> : Nom du produit\n--type=<type> : simple, grouped, external, variable\n--regular_price=<price> : Prix régulier\n--sale_price=<price> : Prix de vente\n--stock_quantity=<qty> : Quantité en stock",
    notes: "Crée un produit simple par défaut. Utilisez --type=variable pour les produits variables",
    category: "WooCommerce",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    command: "wp wc product update <id>",
    description: "Met à jour un produit existant",
    example: "wp wc product update 123 --regular_price=39.99 --sale_price=29.99",
    options: "--name=<name> : Nom\n--regular_price=<price> : Prix régulier\n--sale_price=<price> : Prix de vente\n--description=<desc> : Description\n--short_description=<desc> : Description courte",
    notes: "Permet de modifier toutes les propriétés d'un produit",
    category: "WooCommerce",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    command: "wp wc product delete <id>",
    description: "Supprime définitivement un produit",
    example: "wp wc product delete 123 --force",
    options: "--force : Force la suppression (bypass la corbeille)\n--ids=<ids> : Supprimer plusieurs produits (IDs séparés par des virgules)",
    notes: "ATTENTION : Suppression définitive. Utilisez --force pour bypasser la corbeille",
    category: "WooCommerce",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  {
    command: "wp wc product import <file>",
    description: "Importe des produits depuis un fichier CSV",
    example: "wp wc product import products.csv --update_existing",
    options: "--update_existing : Met à jour les produits existants\n--skip-row=<n> : Ignore les N premières lignes\n--delimiter=<char> : Délimiteur CSV",
    notes: "Format CSV compatible avec l'export WooCommerce. Faites un backup avant l'import !",
    category: "WooCommerce",
    difficulty: "avancé",
    isFavorite: false,
  },
  {
    command: "wp wc product export",
    description: "Exporte les produits vers un fichier CSV",
    example: "wp wc product export --output=products-export.csv --format=csv",
    options: "--output=<file> : Fichier de sortie\n--format=<format> : csv, json\n--fields=<fields> : Champs à exporter",
    notes: "Exporte tous les produits avec leurs métadonnées pour sauvegarde ou migration",
    category: "WooCommerce",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  // WooCommerce - Gestion des Commandes
  {
    command: "wp wc order list",
    description: "Liste toutes les commandes WooCommerce",
    example: "wp wc order list --status=processing --format=table",
    options: "--status=<status> : pending, processing, on-hold, completed, cancelled, refunded, failed\n--format=<format> : table, csv, json\n--per_page=<n> : Nombre de résultats",
    notes: "Filtrez par statut pour voir les commandes en attente, complétées, etc.",
    category: "WooCommerce",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    command: "wp wc order get <id>",
    description: "Obtenir les détails complets d'une commande",
    example: "wp wc order get 456 --format=json",
    options: "--format=<format> : table, json, yaml\n--fields=<fields> : Champs spécifiques",
    notes: "Affiche toutes les informations : produits, client, adresses, paiement, etc.",
    category: "WooCommerce",
    difficulty: "débutant",
    isFavorite: true,
  },
  {
    command: "wp wc order create",
    description: "Crée une commande manuellement",
    example: "wp wc order create --customer_id=5 --payment_method='bacs' --status=processing",
    options: "--customer_id=<id> : ID du client\n--payment_method=<method> : Méthode de paiement\n--status=<status> : Statut de la commande\n--line_items=<json> : Articles de la commande (JSON)",
    notes: "Utile pour créer des commandes manuelles ou tester le système",
    category: "WooCommerce",
    difficulty: "avancé",
    isFavorite: false,
  },
  {
    command: "wp wc order update <id>",
    description: "Met à jour une commande existante",
    example: "wp wc order update 456 --status=completed",
    options: "--status=<status> : Nouveau statut\n--customer_id=<id> : Changer le client\n--billing=<json> : Adresse de facturation (JSON)",
    notes: "Change le statut, le client ou les adresses d'une commande",
    category: "WooCommerce",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  {
    command: "wp wc order delete <id>",
    description: "Supprime définitivement une commande",
    example: "wp wc order delete 456 --force",
    options: "--force : Force la suppression (bypass la corbeille)",
    notes: "ATTENTION : Suppression définitive. Les commandes sont importantes pour la comptabilité !",
    category: "WooCommerce",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  {
    command: "wp wc order refund <id>",
    description: "Crée un remboursement pour une commande",
    example: "wp wc order refund 456 --amount=29.99 --reason='Produit défectueux'",
    options: "--amount=<amount> : Montant du remboursement\n--reason=<reason> : Raison du remboursement\n--api_refund=true : Remboursement via l'API du processeur",
    notes: "Crée un remboursement partiel ou total. Utilisez --api_refund pour rembourser via la passerelle de paiement",
    category: "WooCommerce",
    difficulty: "avancé",
    isFavorite: false,
  },
  // WooCommerce - Gestion des Coupons
  {
    command: "wp wc coupon list",
    description: "Liste tous les coupons de réduction",
    example: "wp wc coupon list --format=table",
    options: "--format=<format> : table, csv, json\n--per_page=<n> : Nombre de résultats\n--status=<status> : active, expired, used",
    notes: "Vue d'ensemble de tous les codes promo disponibles",
    category: "WooCommerce",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    command: "wp wc coupon create",
    description: "Crée un nouveau coupon de réduction",
    example: "wp wc coupon create --code=SUMMER20 --discount_type=percent --amount=20",
    options: "--code=<code> : Code du coupon\n--discount_type=<type> : fixed_cart, fixed_product, percent\n--amount=<amount> : Montant ou pourcentage\n--expiry_date=<date> : Date d'expiration",
    notes: "Crée un coupon avec réduction fixe ou pourcentage. Définissez --expiry_date pour limiter la validité",
    category: "WooCommerce",
    difficulty: "intermédiaire",
    isFavorite: true,
  },
  {
    command: "wp wc coupon update <id>",
    description: "Met à jour un coupon existant",
    example: "wp wc coupon update 789 --amount=25 --expiry_date=2024-12-31",
    options: "--amount=<amount> : Nouveau montant\n--expiry_date=<date> : Nouvelle date d'expiration\n--usage_limit=<n> : Limite d'utilisation",
    notes: "Modifie les propriétés d'un coupon (montant, validité, limites)",
    category: "WooCommerce",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  {
    command: "wp wc coupon delete <id>",
    description: "Supprime définitivement un coupon",
    example: "wp wc coupon delete 789 --force",
    options: "--force : Force la suppression",
    notes: "Supprime un coupon. Les coupons utilisés restent dans l'historique",
    category: "WooCommerce",
    difficulty: "débutant",
    isFavorite: false,
  },
  // WooCommerce - Gestion des Clients
  {
    command: "wp wc customer list",
    description: "Liste tous les clients WooCommerce",
    example: "wp wc customer list --format=table --per_page=50",
    options: "--format=<format> : table, csv, json\n--per_page=<n> : Nombre de résultats\n--email=<email> : Filtrer par email",
    notes: "Affiche tous les clients ayant passé commande sur la boutique",
    category: "WooCommerce",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    command: "wp wc customer get <id>",
    description: "Obtenir les détails d'un client",
    example: "wp wc customer get 10 --format=json",
    options: "--format=<format> : table, json, yaml\n--fields=<fields> : Champs spécifiques",
    notes: "Affiche les informations client : commandes, adresses, métadonnées",
    category: "WooCommerce",
    difficulty: "débutant",
    isFavorite: false,
  },
  {
    command: "wp wc customer create",
    description: "Crée un nouveau client WooCommerce",
    example: "wp wc customer create --email=client@example.com --first_name=Jean --last_name=Dupont",
    options: "--email=<email> : Email (requis)\n--first_name=<name> : Prénom\n--last_name=<name> : Nom\n--username=<user> : Nom d'utilisateur",
    notes: "Crée un client avec ses informations de base. L'email doit être unique",
    category: "WooCommerce",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  // WooCommerce - Utilitaires
  {
    command: "wp wc tool run <tool>",
    description: "Exécute un outil de maintenance WooCommerce",
    example: "wp wc tool run clear_transients",
    options: "<tool> : clear_transients, clear_template_cache, regenerate_thumbnails\n--dry-run : Simule sans appliquer",
    notes: "Outils de maintenance pour nettoyer le cache, régénérer les miniatures, etc.",
    category: "WooCommerce",
    difficulty: "intermédiaire",
    isFavorite: false,
  },
  {
    command: "wp wc report",
    description: "Génère des rapports WooCommerce",
    example: "wp wc report sales --period=last_month",
    options: "--type=<type> : sales, customers, products\n--period=<period> : last_week, last_month, last_year\n--format=<format> : table, json",
    notes: "Génère des rapports de ventes, clients ou produits pour analyser les performances",
    category: "WooCommerce",
    difficulty: "avancé",
    isFavorite: false,
  },
];
